[workspace]
members = [
    # -- Libraries
    "zms-tradition-proto-grpc-types",

    # -- Binaries

]
default-members = [
    # -- Libraries
    "zms-tradition-proto-grpc-types",

    # -- Binaries

]
resolver = "2"